### ISSUE TITLE
Phase 2 de l'expérimentation Carte Blanche à Cahors

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-france-local#11]
La phase 2 peut être détaillée en 2 étapes importantes :
![capture d ecran de 2019-01-09 14-15-50](https://user-images.githubusercontent.com/1410356/50901801-8505d280-1419-11e9-862b-ba976a6862f7.png)
![capture d ecran de 2019-01-09 14-15-21](https://user-images.githubusercontent.com/1410356/50901808-8a631d00-1419-11e9-9725-aa126936eae0.png)
![capture d ecran de 2019-01-09 14-15-26](https://user-images.githubusercontent.com/1410356/50901811-8afbb380-1419-11e9-8ce4-9c493b79c8bd.png)

L'amélioration de la qualification est là pour améliorer la pertinence des flux de données réalisés entre les caisses :
![capture d ecran de 2019-01-09 14-15-34](https://user-images.githubusercontent.com/1410356/50901812-8afbb380-1419-11e9-9546-5fa8563282b4.png)

Concrètement, l'objectif de l'expérimentation est de :
- calculer de l'éligibilité à l'ACS et à la CMU-C (prestations CPAM) avec des données CAF de demandes de PPA et de RSA et
- de calculer de l'éligiblité à la PPA ou au RSA à partir des données CPAM.

Après on peut tester la pertinence de l'évaluation en recoupant les estimations avec les résultats d'instructions de demande.
![capture d ecran de 2018-12-06 18-24-15](https://user-images.githubusercontent.com/1410356/49600736-2c5b9980-f984-11e8-8857-616a0fe2b7f8.png)
 

Les limitations actuelles des expérimentations (phase 1 et 2) proviennent selon moi des nombreuses étapes manuelles et automatisables. Les pistes suivantes sont pour cette raison très opérationnelles. 

- Avec tout le monde
  - [ ] Favoriser l'usage de GitHub pour faciliter la collaboration
- CPAM (Oracle 2010 - 10.2.0.5.0) 
  - [ ] Génération de fichiers CSV
    - [ ] Unicité des noms de colonnes (les colonnes TOPx apparaissent comme T uniquement et il est donc impossible de faire la distinction)
    - [ ] Pas de répétition des noms de colonnes toutes les _n_ lignes
    - https://stackoverflow.com/questions/643137/how-do-i-spool-to-a-csv-formatted-file-using-sqlplus
    - Tester le hachage dircetement dans Oracle
    - https://stackoverflow.com/questions/22533037/how-to-call-oracle-md5-hash-function
  - [ ] Importation de fichiers CSV
    - External tables - http://www.orafaq.com/node/848
  - [ ] Créer un script
    - [ ] Lancer en ligne de commande
      - https://stackoverflow.com/questions/1639704/sqlplus-statement-from-command-line/1639930#1639930
    - [ ] Avec des arguments
      - https://stackoverflow.com/questions/18620893/how-do-i-pass-arguments-to-a-pl-sql-script-on-command-line-with-sqlplus#18621153
  - [ ] Regroupement des fichiers dans une archive
  - ~[ ] Envoi automatisé via l'outil de tranfert sécurisé~ (suite échange CPAM, email du 7/12)
    - ~[ ] https://petra.ameli.fr/ est-il utilisable en ligne de commande ou par API~ (suite échange CPAM, email du 7/12)
  - ~[ ] Chiffrement et déchiffrement automatisé via l'outil de la CPAM~ (suite échange CPAM, email du 7/12)
    - ~[ ] Mise en Open-source~ (suite échange CPAM, email du 7/12)
    - ~[ ] Ajout de la possibilité d'utiliser l'executable en ligne de commande~ (suite échange CPAM, email du 7/12)
- CAF
  - [ ] Génération de fichiers CSV
  - [ ] Importation de fichiers CSV
  - [ ] Créer un script
    - [ ] Lancer en ligne de commande
    - [ ] Avec des arguments
  - [ ] Regroupement des fichiers dans une archive

**Comment by PierreCll** [comment]
Thomas, 
Merci pour toute cette documentation. J'ai bien tout analysé et tout est très clair, à l'exception d'un point : je suis pas certain de comprendre la complémentarité de l'usage d'open fisca et de l'échange de données entre 2 organismes. 
J'ai bien compris le processus d'entraînement de l'outil Open Fisca par données internes et externes. Les questions que je me posent sont les suivantes : 
- Une fois que l'entraînement de l'outil Open Fisca est "terminé", est-ce que si le rapprochement des données théoriques Open Fisca et des données issues de l'organisme donne des écarts cela entend qu'Open Fisca sera utilisé comme outil de "data quality" par l'organisme afin de contrôler et nettoyer ses données non cohérentes ? 
- Pour l'enchaînement suivant : 
![image](https://user-images.githubusercontent.com/46572295/50985067-b529a000-1503-11e9-96ad-78f1e893aea5.png)
Je ne suis pas certain de comprendre : est-ce qu'il faudra passer par Open Fisca en phase 2 pour échanger des données avec un autre organisme ? Si oui, pourquoi ? Car l'entraînement de l'outil Open Fisca aura avant également permis aux utilisateurs de bien qualifier les données nécessaires au calcul de prestations externes ? 

Si tu veux, nous pouvons nous appeler - je crois que tu as mon numéro - ou en parler de vive voix lundi après-midi. 

Merci.

**Comment by guillett** [comment]
Merci @PierreCll d'avoir utilisé GitHub !

La phase 2 peut être vue comme l'amélioration de la phase 1.
> Amélioration c'est à dire ?

Si l'intérêt du partage de données comme il a été fait a fait déjà est avéré, ce partage a néanmoins  des faiblesses. C'est particulièrement visible sur la qualification des bénéficiaires potentiels. Pour le dire autrement, il y a beaucoup de faux positifs ce qui génère une charge de travail importante (vérification manuelle dans les dossiers).

L'objectif de la phase 2 et de l'utilisation d'OpenFisca est d'avoir une identification plus fine des bénéficiaires potentiels.

C'est pour cette raison qu'il me parait très important d'automatiser l'évaluation de toutes les stratégies mises en place et expérimentées. Cette automatisation nous permettra de tester de nombreuses stratégies pour choisir la meilleure.

À titre d'exemple, la prime d'activité repose sur les ressources des 3 derniers mois. Ces informations sont donc celles disponibles pour évaluer du droit ACS à partir des données CAF. Cela dit, l'ACS repose sur les ressources des 12 derniers mois. Une hypothèse est donc nécessaire. Les ressources sur les 12 derniers mois sont équivalents à 4 * ceux sur les 3 derniers mois. Sur ce cas précis, la question que je me pose est donc :
- Sur la population connue, quelle est la répartition
  - vrais positifs
  - vrais négatifs
  - faux positifs
  - faux négatifs

Cela est-il plus clair ?

À titre de clarification, les données ne permettent pas d’entraîner OpenFisca mais de nous aider à le fiabiliser pour qu'il corresponde à tous les détails de la législation et aux résultats d'instruction des différents organismes.

**Comment by guillett** [comment]
L'expérimentation Carte Blanche est terminée. Je ferme les issues qui y étaient liées.
